### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by Unstinted** [tarecord/sign-in-with-google#60]
the redirect URI in the request, https://harlunfh.com/?google_response, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}

**Comment by adebo4all** [comment]
You need to update your redirect URI from whatever it is to **https://harlunfh.com/?google_response**, on the **Authorized redirect URIs
section** of the OAuth Client ID page on Google for it to match what it is in the application.

**Comment by ttodua** [comment]
This issue should be closed as I see.
