### ISSUE TITLE
Is development of this plugin discontinued?

### ISSUE THREAD

**Issue by ttodua** [tarecord/sign-in-with-google#95]
We have tried to contact you through email, also comments under PR, but nowhere get response for a very long time.
Can you please say with one word (yes or no) if the plugin is abandoned or not?  we are waiting the PR's to be merged, and if you are no longer interested in the development, we will have to fork it and continue on our own (which I try to refrain from unless you have abandoned this plugin).

**Comment by tarecord** [comment]
Hey, @ttodua yes, I am still planning to maintain this plugin but I have been very busy this year. I should be able to start reviewing your PRs later this week so keep an eye out for that!

Thanks for all the PR's, I really appreciate the time you've invested!
