### ISSUE TITLE
Login Redirect

### ISSUE THREAD

**Issue by ajien** [tarecord/sign-in-with-google#96]
In class-sign-in-with-google-admin.php, line 561, you have 

`wp_redirect( apply_filters( 'login_redirect', $redirect ) );`

with only one argument instead of 3 (https://developer.wordpress.org/reference/hooks/login_redirect/). This causes error when hooking to 'login_redirect', such as when redirecting based on user role. Will you be able to change it to accept all 3 arguments as documented here: https://developer.wordpress.org/reference/hooks/login_redirect/? Thanks.

**Comment by BenJamesAndo** [comment]
Yes using LoginWP (Formerly Peter's Login Redirect) plugin caused issues. Disabling it made login with Google work.

**Comment by ajien** [comment]
@BenJamesAndo the login works, it's the redirect that's having issue because the login_redirect function required 3 arguments instead of just one. When refreshing the page with the error message, the user is redirected to the backend, which is not always the desired outcome.

**Comment by tarecord** [comment]
I've looked into this and `apply_filters( 'login_redirect' )` shouldn't be used. The plugin should actually be using `add_filter( 'login_redirect' )` instead.
